name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install root package
        run: npm ci

      - name: Lint all packages
        run: npm run lint

      - name: Build all packages
        run: npm run build
